name: "Setup Python Environment"
description: "Setup Python, uv, just, and install dependencies"

inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.14"
  cache-uv:
    description: "Whether to cache uv dependencies"
    required: false
    default: "true"
  install-command:
    description: "Command to install dependencies"
    required: false
    default: "just install-dev"

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: ${{ inputs.cache-uv == 'true' && 'uv' || '' }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"

    - name: Cache uv dependencies
      if: inputs.cache-uv == 'true'
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install just
      uses: extractions/setup-just@v1
      with:
        just-version: "latest"

    - name: Install dependencies
      shell: bash
      run: ${{ inputs.install-command }}
