name: twertb

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Linter
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Tests
      env:
        DATE: "2019-09-04"
      run: |
        set +e
        echo "Test TG"
        ./twertb.py -e EUR RUB -u -t ${{ secrets.TOKEN }} -i ${{ secrets.ID }}
        echo "Test TG with currency"
        ./twertb.py -e EUR RUB -u -a 70 -t ${{ secrets.TOKEN }} -i ${{ secrets.ID }}
        echo "Check when alert uses without database updating"
        ./twertb.py -e EUR RUB -a 69 ; [[ $? -eq 1 ]]
        echo "Check when token or id incorrect"
        ./twertb.py -e EUR RUB -t 123 -i ${{ secrets.ID }} ; [[ $? -eq 1 ]]
        echo "Check when source and target currencies is equal"
        ./twertb.py -e EUR EUR ; [[ $? -eq 1 ]]
