name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Run formatting check
        run: just fmt-check

      - name: Run linting
        run: just lint

  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests with coverage
        uses: ./.github/actions/run-tests
        with:
          coverage: true
          upload-coverage: true

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build package
        uses: ./.github/actions/build-package
        with:
          upload-artifacts: true
