name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: venv
          key: ${{ runner.os }}-venv-3.13-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-venv-3.13-

      - name: Install dependencies
        run: |
          make install-dev

      - name: Run linting
        run: |
          make lint

      - name: Run tests
        run: |
          make test

      - name: Build package
        run: |
          make build
