name: Release Pipeline

on:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for changelog generation

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Build package
        run: |
          make build

      - name: Get package version
        id: package_version
        run: |
          # Extract version from the built wheel file
          WHEEL_FILE=$(ls dist/wiserate-*-py3-none-any.whl | head -1)
          if [ -z "$WHEEL_FILE" ]; then
            echo "Error: No wheel file found in dist/"
            exit 1
          fi
          VERSION=$(echo "$WHEEL_FILE" | sed 's/wiserate-\(.*\)-py3-none-any.whl/\1/')
          if [ -z "$VERSION" ]; then
            echo "Error: Could not extract version from wheel file: $WHEEL_FILE"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Found version: $VERSION"

      - name: Generate changelog
        id: changelog
        run: |
          # Get the current tag (triggered by tag push)
          CURRENT_TAG=${GITHUB_REF#refs/tags/}

          # Get the previous release tag
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")

          # Generate changelog directly without creating a file
          if [ -z "$PREVIOUS_TAG" ]; then
            # First release, get all commits
            CHANGELOG=$(python scripts/generate_changelog.py ${{ steps.package_version.outputs.version }} --stdout)
          else
            # Get commits since last release
            CHANGELOG=$(python scripts/generate_changelog.py ${{ steps.package_version.outputs.version }} $PREVIOUS_TAG --stdout)
          fi

          # Check if changelog generation was successful
          if [ $? -ne 0 ] || [ -z "$CHANGELOG" ]; then
            echo "Warning: Changelog generation failed or empty, using fallback"
            CHANGELOG="## Release ${{ steps.package_version.outputs.version }}"
          fi

          # Set output for next steps
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.package_version.outputs.version }}
          body: |
            ## What's Changed

            ${{ steps.changelog.outputs.changelog }}

            ## Installation

            ```bash
            pip install git+https://github.com/Amet13/WiseRate.git@v${{ steps.package_version.outputs.version }}
            ```

            ## Usage

            ```bash
            wiserate --help
            ```

            ## Documentation

            See [README.md](README.md) for full documentation.
          files: |
            dist/wiserate-${{ steps.package_version.outputs.version }}-*.whl
            dist/wiserate-${{ steps.package_version.outputs.version }}.tar.gz
          draft: false
          prerelease: false
